//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSane.L10n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSane.L10n.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        internal static string EXCEPTION_ACCESS_DENIED {
            get {
                return ResourceManager.GetString("EXCEPTION_ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string EXCEPTION_CANCELED {
            get {
                return ResourceManager.GetString("EXCEPTION_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Open.
        /// </summary>
        internal static string EXCEPTION_COVER_OPEN {
            get {
                return ResourceManager.GetString("EXCEPTION_COVER_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Busy.
        /// </summary>
        internal static string EXCEPTION_DEVICE_BUSY {
            get {
                return ResourceManager.GetString("EXCEPTION_DEVICE_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of File.
        /// </summary>
        internal static string EXCEPTION_END_OF_FILE {
            get {
                return ResourceManager.GetString("EXCEPTION_END_OF_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Operation.
        /// </summary>
        internal static string EXCEPTION_INVALID_OPERATION {
            get {
                return ResourceManager.GetString("EXCEPTION_INVALID_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Error.
        /// </summary>
        internal static string EXCEPTION_IO_ERROR {
            get {
                return ResourceManager.GetString("EXCEPTION_IO_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No document.
        /// </summary>
        internal static string EXCEPTION_NO_DOCUMENT {
            get {
                return ResourceManager.GetString("EXCEPTION_NO_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Memory.
        /// </summary>
        internal static string EXCEPTION_OUT_OF_MEMORY {
            get {
                return ResourceManager.GetString("EXCEPTION_OUT_OF_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Jammed.
        /// </summary>
        internal static string EXCEPTION_PAPER_JAMMED {
            get {
                return ResourceManager.GetString("EXCEPTION_PAPER_JAMMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown SANE Error Code.
        /// </summary>
        internal static string EXCEPTION_UNKNOWN {
            get {
                return ResourceManager.GetString("EXCEPTION_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported SANE Call.
        /// </summary>
        internal static string EXCEPTION_UNSUPPORTED {
            get {
                return ResourceManager.GetString("EXCEPTION_UNSUPPORTED", resourceCulture);
            }
        }
    }
}
